### ISSUE TITLE
[14.0] auth_saml tests broken

### ISSUE THREAD

**Issue by simahawk** [OCA/server-auth#330] opened 2022-01-14 09:12 UTC
```
ERROR: TestPySaml.test_ensure_get_auth_request_redirects
Traceback (most recent call last):
  File "/home/travis/build/OCA/server-auth/setup/auth_saml/odoo/addons/auth_saml/tests/test_pysaml.py", line 27, in setUp
    "idp_metadata": FakeIDP().get_metadata(),
  File "/home/travis/build/OCA/server-auth/setup/auth_saml/odoo/addons/auth_saml/tests/fake_idp.py", line 116, in __init__
    Server.__init__(self, config=config)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/saml2/server.py", line 89, in __init__
    Entity.__init__(self, stype, config, config_file, msg_cb=msg_cb)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/saml2/entity.py", line 187, in __init__
    self.sec = security_context(self.config)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/saml2/sigver.py", line 1030, in security_context
    xmlsec_binary = get_xmlsec_binary(_path)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/saml2/sigver.py", line 210, in get_xmlsec_binary
    raise SigverError('Cannot find {binary}'.format(binary=bin_name))
saml2.sigver.SigverError: Cannot find ['xmlsec1']
```

https://app.travis-ci.com/github/OCA/server-auth/jobs/555592400#L1505

**Comment by theangryangel** [comment] 2022-01-14 10:00
This seems to be caused by this commit? They were passing when auth_saml was originally merged afaik.

https://github.com/OCA/server-auth/commit/cf2e6853babd1da634201f92e546f19c5651a3a9#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485L15

**Comment by simahawk** [comment] 2022-01-14 10:05
@theangryangel my bad :sob: OTOH that lib should have been listed into .copier-answers.yml :wink: 
I'll fix it. Thanks for the feedback!

**Comment by theangryangel** [comment] 2022-01-14 10:11
Noted, I'll double check that in future! Thanks for the pointer @simahawk <3

**Closed as completed** 2022-01-14 12:07 UTC
Labels: bug
