### ISSUE TITLE
How to install lasso module

### ISSUE THREAD

**Issue by shyjuk** [OCA/server-auth#24] opened 2018-05-31 11:09 UTC
module: auth_saml
version: 11.0

**Steps to reproduce**
- ...

**Current behavior**

**Expected behavior**

**Comment by pedrobaeza** [comment] 2018-05-31 11:10
Sorry, this is not an Odoo issue, but a question. You should make it on Odoo official forums (https://www.odoo.com/forum/help-1) or mailing lists (https://odoo.com/groups), but not here.

Closing this by the reason above.

**Closed as completed by pedrobaeza** 2018-05-31 11:10 UTC

**Comment by shyjuk** [comment] 2018-06-03 11:22
I have installed lasso with command  apt install python-lasso
import lasso also works from the python command line.
But still the module complaints "No module named lasso"

**Comment by phong-innomizetech** [comment] 2018-12-07 09:44
@shyjuk Did you find out the root cause?

**Comment by smurf-U** [comment] 2020-05-25 17:30
Any update? @shyjuk
